<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>RATools.Api</AssemblyName>
    <RootNamespace>RATools.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RATools.Application\RATools.Application.csproj" />
    <ProjectReference Include="..\RATools.Infrastructure\RATools.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="App_Data\**" />
    <None Remove="App_Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
