// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RATools.Infrastructure.Persistence.EfCore;

#nullable disable

namespace RATools.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(RAToolsDbContext))]
    [Migration("20260811131515_MaterializePublishHistorySummary")]
    partial class MaterializePublishHistorySummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.ApplicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EctdTemplateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WorkingDirectoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationNumber");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.AuditLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc")
                        .IsDescending();

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.DocumentPlacementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CtdSection")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LifecycleTargetPlacementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SequenceNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("LifecycleTargetPlacementId");

                    b.HasIndex("ApplicationId", "SequenceNumber");

                    b.ToTable("document_placements", (string)null);
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.PublishJobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("HistoryArtifactFileCount")
                        .HasColumnType("integer");

                    b.Property<long?>("HistoryArtifactPackageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("HistoryArtifactTotalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("HistoryLifecycleAmbiguousCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoryLifecycleAppendTargetNotFoundCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoryLifecycleCurrentSequenceCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoryLifecycleDeleteTargetNotFoundCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoryLifecycleMatchedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoryLifecycleReplaceTargetNotFoundCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoryReadinessBlockingErrorCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("HistoryReadinessIsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("HistoryReadinessMissingMetadataFieldsJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("HistoryReadinessStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("HistoryReadinessWarningCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("HistoryReportAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("HistoryReportError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("HistoryReportPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool?>("HistoryReportReadable")
                        .HasColumnType("boolean");

                    b.Property<int?>("HistoryValidationErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("HistoryValidationProfile")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("HistoryValidationWarningCount")
                        .HasColumnType("integer");

                    b.Property<string>("HistoryValidationWarningSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeaseExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PackagePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SequenceNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "CreatedUtc");

                    b.HasIndex("ApplicationId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Pending', 'Running')");

                    b.HasIndex("Status", "LeaseExpiresUtc");

                    b.HasIndex("ApplicationId", "HistoryReadinessStatus", "CreatedUtc");

                    b.HasIndex("ApplicationId", "SequenceNumber", "CreatedUtc");

                    b.HasIndex("ApplicationId", "SequenceNumber", "Status");

                    b.HasIndex("Status", "NextAttemptUtc", "CreatedUtc");

                    b.ToTable("publish_jobs", (string)null);
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.SequenceRecord", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SequenceNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FdaApplicantContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FdaApplicantContactType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FdaApplicantName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FdaApplicationType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FdaEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FdaFormType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FdaSequenceDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FdaSubmissionSubtype")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FdaSubmissionType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FdaTelephone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FdaTelephoneNumberType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ApplicationId", "SequenceNumber");

                    b.ToTable("sequences", (string)null);
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.DocumentPlacementRecord", b =>
                {
                    b.HasOne("RATools.Infrastructure.Persistence.EfCore.ApplicationRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RATools.Infrastructure.Persistence.EfCore.DocumentRecord", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RATools.Infrastructure.Persistence.EfCore.SequenceRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId", "SequenceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.SequenceRecord", b =>
                {
                    b.HasOne("RATools.Infrastructure.Persistence.EfCore.ApplicationRecord", null)
                        .WithMany("Sequences")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RATools.Infrastructure.Persistence.EfCore.ApplicationRecord", b =>
                {
                    b.Navigation("Sequences");
                });
#pragma warning restore 612, 618
        }
    }
}
